apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources: []
#  - cashback-service.yaml
#  - cryptocard-accounting.yaml
#  - cryptocard-aml.yaml
#  - cryptocard-management-events.yaml
#  - cryptocard-manager.yaml
#  - cryptocard-reports.yaml
#  - cryptocard-topup.yaml
#  - gasless.yaml
#  - verestro-factory.yaml
#  - admin-manager.yaml
