apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - app-secret.enc.yaml
  - ./overlays/arbitrum
  - ./overlays/aurora
  - ./overlays/avalanche
  - ./overlays/bitcoin
  - ./overlays/bsc
  - ./overlays/ethereum
  - ./overlays/fantom
  - ./overlays/gnosis
  - ./overlays/linea
  - ./overlays/litecoin
  - ./overlays/near
  - ./overlays/optimism
  - ./overlays/polygon
  - ./overlays/polygon-testnet
  - ./overlays/solana
  - ./overlays/tron
  - ./overlays/zksync
