apiVersion: v1
kind: ConfigMap
metadata:
  name: common-env-cm
  namespace: apps
data:
  HEALTH_HOST: 0.0.0.0
  HEALTH_PORT: "3100"
  HTTP_PORT: "3000"
  NATS_SERVERS: nats-0.nats-headless.nats:4222,nats-1.nats-headless.nats:4222,nats-2.nats-headless.nats:4222
  REDIS_HOST: redis-master.redis
  REDIS_PORT: "6379"
  POSTGRES_HOST: 127.0.0.1
  POSTGRES_PORT: "5000"
  POSTGRES_CASBIN_DATABASE: uta_casbin
  POSTGRES_CASBIN_USER: pg-uta-casbin@stage-uta-stack.iam
